# Generated by Django 3.2.22 on 2023-10-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['otdel'], 'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name_hotel',
        ),
        migrations.AddField(
            model_name='contact',
            name='FIO',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='contact',
            name='otdel',
            field=models.CharField(default='', max_length=150, verbose_name='Отдел'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
