# Generated by Django 3.2.22 on 2023-10-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20231014_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Телефон'),
        ),
    ]
