# Generated by Django 3.2.21 on 2023-10-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('descr', models.CharField(max_length=1000, verbose_name='Название')),
                ('ds', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('du', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, default='', upload_to='hotel/photos', verbose_name='фото')),
                ('ds', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('du', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='RoomOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('du', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.option', verbose_name='Опция')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.room', verbose_name='Номер')),
            ],
        ),
    ]
