# Generated by Django 3.2.21 on 2023-10-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomoptions',
            old_name='option_id',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='roomoptions',
            old_name='room_id',
            new_name='room',
        ),
    ]
