# Generated by Django 3.2.21 on 2023-10-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20231011_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
    ]
