# Generated by Django 3.2.21 on 2023-10-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['name'], 'verbose_name': 'Опция', 'verbose_name_plural': 'Опции'},
        ),
        migrations.AlterModelOptions(
            name='roomoptions',
            options={'ordering': ['room', 'option'], 'verbose_name': 'Номер-опция', 'verbose_name_plural': 'Номер-опция'},
        ),
        migrations.AlterField(
            model_name='option',
            name='descr',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Название'),
        ),
    ]
