# Generated by Django 3.2.22 on 2023-10-14 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20231011_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='photo',
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='', upload_to='hotel/photos', verbose_name='фото')),
                ('ds', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('du', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.room', verbose_name='Номер')),
            ],
        ),
    ]
