# Generated by Django 3.2.22 on 2023-10-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20231014_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomphoto',
            options={'ordering': ['room'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=2, verbose_name='Вместимость'),
        ),
    ]
