# Generated by Django 3.2.22 on 2023-10-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20231018_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер комнаты')),
                ('etag', models.IntegerField(verbose_name='Этаж"')),
                ('ds', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('du', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.room', verbose_name='Тип номера')),
            ],
        ),
    ]
