# Generated by Django 3.2.22 on 2023-10-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_roomnumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'verbose_name': 'Тип номера', 'verbose_name_plural': 'Типы номеров'},
        ),
        migrations.AlterModelOptions(
            name='roomnumber',
            options={'ordering': ['room', 'number'], 'verbose_name': 'Номера комнат', 'verbose_name_plural': 'Номер комнаты'},
        ),
        migrations.AlterModelOptions(
            name='roomoptions',
            options={'ordering': ['room', 'option'], 'verbose_name': 'Тип номера-опция', 'verbose_name_plural': 'Тип номера-опция'},
        ),
        migrations.AlterField(
            model_name='roomnumber',
            name='etag',
            field=models.IntegerField(verbose_name='Этаж'),
        ),
    ]
