# Generated by Django 3.2.22 on 2023-10-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20231019_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomnumber',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Номер комнаты'),
        ),
        migrations.AlterUniqueTogether(
            name='roomoptions',
            unique_together={('room', 'option')},
        ),
    ]
