# Generated by Django 3.2.22 on 2023-10-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.CharField(default='', max_length=2000, verbose_name='Сообщение'),
            preserve_default=False,
        ),
    ]
