# Generated by Django 3.2.22 on 2023-10-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20231014_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'Создана'), (1, 'Просмотрена'), (2, 'Закрыта'), (3, 'Не получилось связаться')], default=0, max_length=1),
        ),
    ]
