# Generated by Django 3.2.22 on 2023-10-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedback_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-ds'], 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
    ]
