# Generated by Django 3.2.22 on 2023-10-14 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_feedback_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус')),
                ('ds', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-ds'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.statusfeedback', verbose_name='Статус обращения'),
        ),
    ]
