# Generated by Django 3.2.22 on 2023-10-19 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0009_auto_20231019_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(verbose_name='дата date_in')),
                ('date_out', models.DateField(verbose_name='дата date_out')),
                ('count_adult', models.IntegerField(verbose_name='count_adult')),
                ('comment', models.TextField(blank=True, default='', max_length=5000, verbose_name='Комментарий')),
                ('FIO', models.CharField(help_text='Введите ФИО', max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('ds', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('du', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.room', verbose_name='Тип номера')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.roomnumber', verbose_name='Номер комнат')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирование',
                'ordering': ['date_in', 'date_out', 'room', 'room_number'],
            },
        ),
    ]
