# Generated by Django 3.2.22 on 2023-10-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='FIO',
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='', help_text='Введите имя', max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='patronymic',
            field=models.CharField(default='', help_text='Введите отчество', max_length=100, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='surname',
            field=models.CharField(default='', help_text='Введите фамилию', max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
