# Generated by Django 3.2.22 on 2023-10-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20231021_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='patronymic',
            field=models.CharField(blank=True, default='', help_text='Введите отчество', max_length=100, verbose_name='Отчество'),
        ),
    ]
