# Generated by Django 3.2.22 on 2023-10-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20231019_0014'),
        ('booking', '0003_alter_booking_patronymic'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('ds', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('du', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-ds', 'date_in', 'date_out', 'room', 'room_number'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирование'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.roomnumber', verbose_name='Номер комнаты'),
        ),
    ]
