# Generated by Django 3.2.22 on 2023-10-25 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20231025_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusbooking',
            options={'ordering': ['-ds'], 'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='booking.statusbooking', verbose_name='Статус'),
        ),
    ]
