# Generated by Django 3.2.22 on 2023-10-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_count_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_booking',
            field=models.CharField(default='20231027-089eaa4f-736b-40a9-9106-18b2f0d9f580', max_length=50, verbose_name='Номер бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='count_adult',
            field=models.IntegerField(verbose_name='Гости'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_in',
            field=models.DateField(verbose_name='дата заезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_out',
            field=models.DateField(verbose_name='дата отъезда'),
        ),
    ]
