# Generated by Django 3.2.22 on 2023-10-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20231027_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_booking',
            field=models.CharField(default='20231027-e6d88f80-2728-432d-bc84-01eb34a0fb2c', max_length=50, unique=True, verbose_name='Номер бронирования'),
        ),
    ]
