# Generated by Django 3.2.22 on 2023-10-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_number_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_booking',
            field=models.CharField(default='20231027-353b857f', max_length=50, unique=True, verbose_name='Номер бронирования'),
        ),
    ]
