# Generated by Django 3.2.22 on 2023-10-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20231028_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusbooking',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование'),
        ),
    ]
